# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495162c43fac278e0469ce2265d12a790700c3d080e2a66c1cd3389645ada7fef1bb2c31cbe39529b7850f3788060f45ff29514b81309f1640d1321dde097089

test:
  secret_key_base: 5f483119b0a47cea44d1649b585b1b5c25ca43decc262f749f42b8b298535b33de3dd7ea5e31bdbcb099ff774daf5ec177a7879d500c93e210af09614eb216b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
